### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: <exception str() failed>

### ISSUE THREAD

**Issue by PR1706** [d-acharya/CovPoolFER#10]
I am running this code, after training several epochs on the two data sets, this error will occur, can you give me some advice? Thank you.
Traceback (most recent call last):
  File "src/train.py", line 330, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train.py", line 192, in main
    args.learning_rate_schedule_file)
  File "src/train.py", line 229, in train
    err, _, _, step, reg_loss = sess.run([loss, train_op, redun, global_step, regularization_losses], feed_dict=feed_dict)
  File "/home/miao/.conda/envs/tensorflow_1.2.0/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/miao/.conda/envs/tensorflow_1.2.0/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/miao/.conda/envs/tensorflow_1.2.0/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/miao/.conda/envs/tensorflow_1.2.0/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: <exception str() failed>

**Comment by Fansgithub2019** [comment]
I have the same problem. Have you solved it?

**Comment by PR1706** [comment]
Sorry, I can not solve the problem. I have tried some methods to solve it, but it faild.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JFanL"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 上午8:11
收件人:&nbsp;"d-acharya/CovPoolFER"<CovPoolFER@noreply.github.com&gt;;
抄送:&nbsp;"ZRL"<349177893@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [d-acharya/CovPoolFER] tensorflow.python.framework.errors_impl.InvalidArgumentError: <exception str() failed&gt; (#10)




I have the same problem. Have you solved it?

**Comment by Fansgithub2019** [comment]
I solved it. In sess, the normalized place went wrong. 
mean, var = tf.nn.moments(m, axes=[2]) leads to tf.nn.batch_normalization(x=m, mean=mean, variance =var, offset=shift, scale=scale, variance_epsilon=0) The data does not correspond (the number of digits is different) and cannot be calculated. 
It needs to be changed to mean, var = tf.nn.moments(m, axes=[0,1, 2]), it is solved.

**Comment by PR1706** [comment]
Where is the code "mean, var = tf.nn.moments(m, axes=[2])"?
I can't find it.
Please help me. Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JFanL"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 上午8:43
收件人:&nbsp;"d-acharya/CovPoolFER"<CovPoolFER@noreply.github.com&gt;;
抄送:&nbsp;"ZRL"<349177893@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [d-acharya/CovPoolFER] tensorflow.python.framework.errors_impl.InvalidArgumentError: <exception str() failed&gt; (#10)




I solved it. In sess, the normalized place went wrong.
 mean, var = tf.nn.moments(m, axes=[2]) leads to tf.nn.batch_normalization(x=m, mean=mean, variance =var, offset=shift, scale=scale, variance_epsilon=0) The data does not correspond (the number of digits is different) and cannot be calculated.
 It needs to be changed to mean, var = tf.nn.moments(m, axes=[0,1, 2]), it is solved.
